title: Mahzabin Karim
description: I'm a final Year student at the Unversity of Toronto studying Civil Engineering. I have extensive experience in construction engineering and geotechnical engineering through many projects and internships.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
logo: assets/img/mazziPic.png